/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class EmergencyChannel extends javax.swing.JFrame {

    public EmergencyChannel() {
        initComponents();
        setResizable(false);
        //Add icon to the frame
        setIcon();
        int x = 10;
        int y = 10;
        int width = 100;
        int height = 100;
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            // Add a window listener to the frame
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Display a JOptionPane when the user closes the subpage
                int choice = JOptionPane.showConfirmDialog(
                        EmergencyChannel.this,
                        "Are you sure you want to go back to the main page?",
                        "Exit Confirmation",
                        JOptionPane.YES_NO_OPTION
                );
                if (choice == JOptionPane.YES_OPTION) {
                    // User chose to go back to the login page
                    MainPage jf= new MainPage();
                    jf.show();
                    dispose();
                }
                // If the user chose "No" or closed the JOptionPane, do nothing and keep the subpage open
            }
        });
    }
    
    private void setIcon() {
        try {
            // Provide the direct URL of the icon image
            URL url = new URL("https://th.bing.com/th/id/OIP.NNnB8HbUoQ91zH1Am383AwHaHa?rs=1&pid=ImgDetMain");  
            ImageIcon icon = new ImageIcon(url);

            // Set the icon image for the frame
            setIconImage(icon.getImage());
        } catch (Exception e) {
            // Handle exceptions
            System.err.println("Error setting icon: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        byes = new javax.swing.JButton();
        bno = new javax.swing.JButton();
        bbackloginpage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emergency Channel");

        jPanel1.setBackground(new java.awt.Color(51, 102, 0));

        jLabel1.setFont(new java.awt.Font("Kohinoor Bangla", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Emergency Channel");

        jPanel2.setBackground(new java.awt.Color(154, 171, 137));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Kohinoor Bangla", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Are you in an Emergency?");

        byes.setBackground(new java.awt.Color(0, 73, 83));
        byes.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        byes.setForeground(new java.awt.Color(255, 255, 255));
        byes.setText("Yes");
        byes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byesActionPerformed(evt);
            }
        });

        bno.setBackground(new java.awt.Color(0, 73, 83));
        bno.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        bno.setForeground(new java.awt.Color(255, 255, 255));
        bno.setText("No");
        bno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(byes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(bno, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(byes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        bbackloginpage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bbackloginpage.setForeground(new java.awt.Color(51, 102, 0));
        bbackloginpage.setText("back to main page");
        bbackloginpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbackloginpageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bbackloginpage, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(bbackloginpage)
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void byesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byesActionPerformed
        StringBuilder output = new StringBuilder();

        // 1st Information: Name
        String name = JOptionPane.showInputDialog(null, "Please enter your name:", "Emergency Channel", 
                JOptionPane.INFORMATION_MESSAGE);
        if (name == null) {
            JOptionPane.showMessageDialog(null, "Emergency Communication Channel has been canceled.", "Emergency Channel", 
                    JOptionPane.INFORMATION_MESSAGE);
            return; // Exit the program if the user pressed "Cancel"
        } else if (name.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Emergency Communication Channel has been canceled. (Error: No name entered)", 
                    "Emergency Channel", JOptionPane.INFORMATION_MESSAGE);
            return; // Exit the program if the user did not enter a name
        } else {
            output.append("User information is written below:\n1. Name: ").append(name).append("\n");
        }

        // 2nd Information: Location
        String[] locationOptions = {"Subang", "Damansara", "Shah Alam", "Puchong", "Kelana Jaya", "Petaling Jaya"};
        String selectedLocation = (String) JOptionPane.showInputDialog(
        null,"We are from Petaling District Emergency Channel. Please select which city you are currently at:",
        "Emergency Channel",JOptionPane.QUESTION_MESSAGE,null,locationOptions,locationOptions[0]);

        if (selectedLocation == null) {
            JOptionPane.showMessageDialog(null, "Emergency Communication Channel has been canceled.", 
                    "Emergency Channel", JOptionPane.INFORMATION_MESSAGE);
            return; // Exit the program if the user pressed "Cancel"
        } else {
            output.append("2. Location: ").append(selectedLocation).append("\n");
        }

        // 3rd Information: Number of People
        String[] numberOfPeopleOptions = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "More than 10"};
        String numberOfPeopleChoice = (String) JOptionPane.showInputDialog(
        null, "Please choose the number of people are there with you (including yourself):","Emergency Channel",
        JOptionPane.QUESTION_MESSAGE,null,numberOfPeopleOptions,numberOfPeopleOptions[0]);

        if (numberOfPeopleChoice == null) {
            JOptionPane.showMessageDialog(null, "Emergency Communication Channel has been canceled.", 
                    "Emergency Channel", JOptionPane.INFORMATION_MESSAGE);
            return; // Exit the program if the user pressed "Cancel"
        } else {
            output.append("3. Number of People: ").append(numberOfPeopleChoice).append("\n");
        }

        // If there are presence of Children
        String[] numberOfChildren = {"No Children", "1", "2", "3 or More"};
        String numberOfChildrenChoice = (String) JOptionPane.showInputDialog(
        null,"Are there any children(s) with you? (Select 'No Children' if there is none):",
        "Emergency Channel",JOptionPane.QUESTION_MESSAGE,null,numberOfChildren,numberOfChildren[0]
        );

        if (numberOfChildrenChoice == null) {
            JOptionPane.showMessageDialog(null, "Emergency Communication Channel has been canceled.", 
                    "Emergency Channel", JOptionPane.INFORMATION_MESSAGE);
            return; // Exit the program if the user pressed "Cancel"
        } else {
            output.append("4. Children: ").append(numberOfChildrenChoice).append("\n");

            if (!numberOfChildrenChoice.equals("No Children")) {
                int totalPeople = Integer.parseInt(numberOfPeopleChoice);
                int childrenCount = numberOfChildrenChoice.equals("3 or More") ? 3 : Integer.parseInt(numberOfChildrenChoice);

                if (childrenCount > totalPeople) {
                    JOptionPane.showMessageDialog(null, "Emergency Communication Channel has been canceled. "
                            + "(Error: Number of children exceeds total number of people)", "Emergency Channel", 
                            JOptionPane.INFORMATION_MESSAGE);
                    return; // Exit the program if the user pressed "Cancel"
                }
            }
        }
        // Ending message to the output
        output.append("Emergency Communication Channel has ended.\n");
        // Display all user information at once at the end
        JOptionPane.showMessageDialog(null, output.toString(), "Emergency Channel", JOptionPane.INFORMATION_MESSAGE);
        
        MainPage jf = new MainPage();
        jf.show();
        dispose();

    }//GEN-LAST:event_byesActionPerformed

    private void bnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnoActionPerformed
        MainPage jf= new MainPage();
        jf.show();
        dispose();
    }//GEN-LAST:event_bnoActionPerformed

    private void bbackloginpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbackloginpageActionPerformed
        MainPage jf = new MainPage();
        jf.setVisible(true);
        dispose();
    }//GEN-LAST:event_bbackloginpageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmergencyChannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmergencyChannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmergencyChannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmergencyChannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmergencyChannel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbackloginpage;
    private javax.swing.JButton bno;
    private javax.swing.JButton byes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}